# 1. Shelter (Needs a safe place to stay)
shelter_examples = [
    "I need a safe place to stay immediately.",
    "My home has been destroyed; I urgently require shelter.",
    "I am homeless and need a secure place to sleep.",
    "I have lost my house and require temporary shelter.",
    "I need emergency shelter due to the disaster.",
    "I have no roof over my head; please help me find shelter.",
    "I am displaced and need a safe place to stay.",
    "I require shelter as my home is uninhabitable.",
    "Please provide me with temporary housing.",
    "I am seeking a safe refuge due to the crisis.",
    "I need a secure shelter right away.",
    "My family and I have no shelter; we need a safe place.",
    "I am forced to stay outdoors; please offer shelter.",
    "I urgently require a safe place to sleep.",
    "I need shelter from these dangerous conditions.",
    "I have nowhere to go and need a safe home.",
    "I need a secure place to rest until help arrives.",
    "I am homeless after the disaster and require shelter.",
    "Please provide a safe shelter for me and my family.",
    "I need emergency housing immediately.",
    "I need a safe and warm shelter right now.",
    "I have been displaced and need a secure place to stay.",
    "I am in desperate need of temporary shelter.",
    "I require a safe place to live during this crisis.",
    "I have lost my home and need emergency shelter.",
    "I need shelter as soon as possible.",
    "I am in need of a safe place to sleep tonight.",
    "My living situation is unsafe; please provide shelter.",
    "I need a secure place to stay until my home is rebuilt.",
    "I require temporary shelter due to the disaster.",
    "I have been left without a home and need shelter.",
    "I am looking for a safe refuge.",
    "I urgently need shelter from this chaos.",
    "I need to find a secure place to call home.",
    "I have nowhere to stay; please help me find shelter.",
    "I require a safe haven during this emergency.",
    "I need a place to sleep safely tonight.",
    "My house is no longer habitable; I need shelter.",
    "I am homeless and require urgent shelter.",
    "I need emergency housing without delay.",
    "I require a temporary safe house.",
    "I need a secure shelter for my family.",
    "I have been left without shelter after the disaster.",
    "I urgently need a safe place to live.",
    "I need to be housed in a secure environment.",
    "I have lost everything and need shelter.",
    "I require a safe refuge as soon as possible.",
    "I am looking for a temporary home.",
    "I need shelter until I can get back on my feet.",
    "I have no safe place to sleep; please help.",
    "I require emergency housing for survival.",
    "I am seeking shelter due to extreme conditions.",
    "I need a safe haven during these turbulent times.",
    "I have been displaced and urgently need a home.",
    "I require shelter to protect me from the elements.",
    "I need a secure place to live until things improve.",
    "I am without a home and in dire need of shelter.",
    "I need a safe place to rest and recover.",
    "I urgently require a temporary residence.",
    "I need shelter because my home has been destroyed.",
    "I am homeless and need a place to stay safely.",
    "I require a secure, temporary home immediately.",
    "I need emergency shelter since my home is gone.",
    "I have been displaced and need a secure refuge.",
    "I need to find a safe shelter quickly.",
    "I require a place to sleep safely tonight.",
    "I have nowhere to go and need immediate shelter.",
    "I am seeking a secure place to live temporarily.",
    "I need emergency housing to protect my family.",
    "I have been left homeless; please provide shelter.",
    "I urgently require a safe shelter due to the disaster.",
    "I need a secure place to stay during these challenging times.",
    "I require temporary housing as my home is destroyed.",
    "I need a safe and secure shelter now.",
    "I have lost my residence and need immediate housing.",
    "I am in urgent need of a safe place to sleep.",
    "I require a secure shelter to escape dangerous conditions.",
    "I have no shelter and need a safe haven.",
    "I need to be provided with temporary shelter.",
    "I am seeking immediate emergency housing.",
    "I require a safe living space urgently.",
    "I have been displaced and need to find shelter quickly.",
    "I need a secure, temporary place to stay.",
    "I require a safe home to protect my family.",
    "I need shelter immediately due to the ongoing crisis.",
    "I am in dire need of temporary housing.",
    "I require a secure place to rest and recover.",
    "I have nowhere to live; please provide emergency shelter.",
    "I need a safe place to stay until I can rebuild.",
    "I urgently require a shelter for myself and my family.",
    "I have lost my home and need a safe temporary residence.",
    "I need a secure shelter to escape these hazardous conditions.",
    "I require emergency shelter as my home is no longer safe.",
    "I have been left with no shelter; I need a safe place.",
    "I need immediate temporary housing.",
    "I require a secure refuge from the current crisis.",
    "I have no safe place to stay; please help me find shelter.",
    "I urgently need a safe home to survive.",
    "I need emergency shelter since I have nowhere else to go.",
    "I require a secure place to live until the crisis passes."
]

# 2. Food (Needs food and water)
food_examples = [
    "I urgently need food and water for my family.",
    "I have run out of food and water; please help.",
    "I need immediate access to food supplies and clean water.",
    "I am starving and require food and water right away.",
    "Please provide food and water as I have nothing left.",
    "I need help obtaining food and fresh water.",
    "I am in desperate need of meals and drinking water.",
    "I require food and water to survive this crisis.",
    "My supplies are gone; I need food and water immediately.",
    "I need nutritional support; please send food and water.",
    "I have no food left; I urgently require meals.",
    "I need water and food supplies as my stock is depleted.",
    "I am in need of sustenance; please provide food and water.",
    "I urgently require food items and drinking water.",
    "I am hungry and need clean water to drink.",
    "I require immediate help with food and water.",
    "My family has no food or water; please help us.",
    "I am without food; I need something to eat.",
    "I require water for drinking and cooking.",
    "I need food for survival; please send supplies.",
    "I urgently need basic food items and bottled water.",
    "I have been left without food or water; help is needed.",
    "I require emergency food supplies and clean water.",
    "My resources are exhausted; I need food and water.",
    "I need immediate nourishment and hydration.",
    "I have no access to food; I require assistance.",
    "I urgently need food to feed my family.",
    "I need clean water as my supply is contaminated.",
    "I require food and water due to the emergency.",
    "I am in dire need of meals and hydration.",
    "I have run out of groceries; please provide food.",
    "I urgently require food packages and water bottles.",
    "I need basic supplies of food and drinking water.",
    "I am starving and need help with food and water.",
    "I require emergency supplies of food for survival.",
    "I have no food left and need help immediately.",
    "I require a delivery of food and clean water.",
    "I am in desperate need of meals and water.",
    "I have no access to proper nourishment; help needed.",
    "I need food and water to sustain my family.",
    "I urgently require grocery items and water supplies.",
    "I am out of food and need immediate assistance.",
    "I need help with obtaining essential food and water.",
    "I require food and clean water to prevent hunger.",
    "I have run out of basic provisions; please help.",
    "I need food and water to avoid starvation.",
    "I require a food package urgently.",
    "I need assistance with meals and water.",
    "I urgently require food supplies due to the crisis.",
    "I have no provisions; please send food and water.",
    "I need food to keep my family fed.",
    "I require clean water as well as food supplies.",
    "I have been left with no meals; please help.",
    "I need essential groceries and bottled water.",
    "I urgently require nourishment and hydration.",
    "I have no food or water; help is urgently needed.",
    "I require immediate food and water support.",
    "I am in dire need of sustenance.",
    "I need help getting food and safe drinking water.",
    "I have run out of essential food supplies.",
    "I urgently need food and water for survival.",
    "I require emergency support with meals.",
    "I have no access to fresh water and food.",
    "I urgently need to be provided with groceries.",
    "I require food and water packages immediately.",
    "I have exhausted my food supplies; help needed.",
    "I need help with securing basic food and water.",
    "I require food and water to avoid hunger.",
    "I am desperate for meals and clean water.",
    "I urgently need help with food supplies.",
    "I have run out of food and water at home.",
    "I need assistance with obtaining basic nourishment.",
    "I require emergency food aid.",
    "I have no food left and require help.",
    "I need food and water to keep my family alive.",
    "I urgently require food provisions.",
    "I have no meals; please help me secure food.",
    "I need to receive food and water as soon as possible.",
    "I require help to obtain essential groceries.",
    "I have no access to nourishment; please assist.",
    "I urgently need food and water in this crisis.",
    "I have run out of supplies; help with food is needed.",
    "I need immediate support with meals and hydration.",
    "I require food packages to prevent starvation.",
    "I have no food; please provide essential supplies.",
    "I need help with acquiring food and clean water.",
    "I urgently require groceries and water.",
    "I have no resources left; please send food.",
    "I need food and water supplies urgently.",
    "I require nourishment to survive this emergency.",
    "I have run out of food and need help immediately.",
    "I require food aid to sustain my family.",
    "I urgently need essential meals and water.",
    "I have no basic supplies; please help with food.",
    "I need immediate access to food and hydration.",
    "I require grocery supplies and water immediately.",
    "I have been left without food; please assist.",
    "I need help with emergency food supplies.",
    "I require food and water to keep my family nourished."
]

# 3. Medical Assistance (Requires medical help, first aid, or medication)
medical_assistance_examples = [
    "I urgently need medical assistance.",
    "I require immediate first aid.",
    "I need emergency medical help.",
    "I require medical attention for injuries.",
    "I need help with medication and medical supplies.",
    "I urgently need a doctor’s assistance.",
    "I require medical aid due to my injuries.",
    "I need first aid support immediately.",
    "I am injured and require urgent medical care.",
    "I require emergency care and medication.",
    "I need medical help for my severe injuries.",
    "I urgently require a nurse or doctor.",
    "I require urgent first aid assistance.",
    "I need immediate medical treatment.",
    "I require help with critical medical care.",
    "I need emergency medication and first aid.",
    "I require urgent care due to an injury.",
    "I need medical support to treat my wounds.",
    "I urgently need help from a medical professional.",
    "I require emergency medical services.",
    "I need immediate attention for my injuries.",
    "I require first aid for my injuries.",
    "I urgently require a paramedic.",
    "I need help with medical treatment immediately.",
    "I require urgent medical care for my condition.",
    "I need emergency help from healthcare providers.",
    "I require assistance with first aid.",
    "I urgently need medication for my illness.",
    "I need medical assistance for a critical condition.",
    "I require immediate care for my injuries.",
    "I need help with urgent medical needs.",
    "I require emergency support for my health.",
    "I urgently need help from a medical team.",
    "I require first aid for a serious injury.",
    "I need emergency medical attention now.",
    "I require help to treat my wounds.",
    "I urgently need a healthcare provider.",
    "I need immediate first aid for my condition.",
    "I require urgent care to treat my injuries.",
    "I need help with emergency medication.",
    "I urgently require first aid and medical supplies.",
    "I need immediate medical support.",
    "I require urgent healthcare assistance.",
    "I need help from a doctor immediately.",
    "I require emergency medical aid.",
    "I need first aid treatment for my injury.",
    "I urgently need medication to stabilize my condition.",
    "I need medical assistance as soon as possible.",
    "I require emergency first aid services.",
    "I need urgent care for a health emergency.",
    "I require help with immediate medical attention.",
    "I need first aid help due to an accident.",
    "I urgently require a medical professional.",
    "I need assistance with emergency healthcare.",
    "I require immediate treatment for my injury.",
    "I need urgent help with my medical needs.",
    "I require emergency first aid to treat my wounds.",
    "I need a doctor urgently for my condition.",
    "I require immediate medical supplies.",
    "I urgently need help with a health crisis.",
    "I need immediate first aid assistance.",
    "I require urgent medication for my condition.",
    "I need medical help for severe injuries.",
    "I require emergency care and first aid support.",
    "I urgently need a nurse for my injuries.",
    "I need immediate assistance from healthcare providers.",
    "I require urgent medical treatment.",
    "I need help with emergency first aid now.",
    "I urgently require medical care for an injury.",
    "I need immediate help from a healthcare professional.",
    "I require emergency treatment for my injuries.",
    "I need urgent first aid to prevent further harm.",
    "I require immediate medical intervention.",
    "I need help with critical first aid.",
    "I urgently require a medical response.",
    "I need emergency care for a serious injury.",
    "I require immediate help with medical supplies.",
    "I need urgent first aid and healthcare support.",
    "I require medical treatment as soon as possible.",
    "I need immediate help with my critical health needs.",
    "I urgently require emergency first aid.",
    "I need medical care to treat my injuries.",
    "I require urgent attention from a healthcare provider.",
    "I need help with emergency treatment immediately.",
    "I require first aid to manage my injuries.",
    "I urgently need help with medical intervention.",
    "I need emergency medication and care.",
    "I require urgent medical services for my condition.",
    "I need help with immediate healthcare.",
    "I require urgent care to manage my injury.",
    "I need immediate help from a medical team.",
    "I require emergency first aid due to a serious injury.",
    "I need urgent assistance for a health crisis.",
    "I require immediate medical help for my wounds.",
    "I need urgent first aid and treatment.",
    "I require emergency healthcare for my injury.",
    "I need immediate medical support for my condition.",
    "I urgently require treatment from a doctor.",
    "I need first aid and emergency care urgently.",
    "I require immediate help to manage my health emergency."
]

# 4. Transportation (Needs help with evacuation)
transportation_examples = [
    "I need help with transportation for evacuation.",
    "I require immediate evacuation assistance.",
    "I need a ride to safety.",
    "I require transport to leave the dangerous area.",
    "I need help evacuating from this area.",
    "I require immediate transport for evacuation.",
    "I need a vehicle to help me escape.",
    "I require transportation to a safe location.",
    "I need evacuation support immediately.",
    "I require help getting out of this dangerous zone.",
    "I need a ride for evacuation.",
    "I require urgent transportation assistance.",
    "I need help moving to a safe area.",
    "I require evacuation transport now.",
    "I need immediate help leaving this area.",
    "I require a vehicle for evacuation.",
    "I need urgent evacuation support.",
    "I require transport to safety as soon as possible.",
    "I need help evacuating immediately.",
    "I require transportation to escape danger.",
    "I need a ride to evacuate.",
    "I require immediate evacuation transport.",
    "I need help getting to a safe place.",
    "I require urgent transportation to safety.",
    "I need evacuation assistance from this area.",
    "I require transport to a secure location.",
    "I need a vehicle to evacuate.",
    "I require urgent evacuation help.",
    "I need transportation to leave this dangerous area.",
    "I require a ride to safety immediately.",
    "I need help with evacuation transport.",
    "I require immediate help leaving this zone.",
    "I need a vehicle to help me evacuate.",
    "I require urgent transport to a safe area.",
    "I need help moving out of danger.",
    "I require transportation to a secure refuge.",
    "I need a ride for urgent evacuation.",
    "I require immediate transport for safety.",
    "I need help evacuating from the disaster area.",
    "I require transportation to escape the danger.",
    "I need a vehicle to leave this hazardous zone.",
    "I require evacuation assistance now.",
    "I need help getting to safety via transport.",
    "I require urgent transportation assistance for evacuation.",
    "I need evacuation transport to a safe location.",
    "I require a ride to leave this area immediately.",
    "I need help with urgent evacuation.",
    "I require transportation to a secure area.",
    "I need help moving to a safe refuge.",
    "I require immediate evacuation support.",
    "I need a vehicle for urgent evacuation.",
    "I require transport to a safe zone.",
    "I need help evacuating as soon as possible.",
    "I require urgent transportation for evacuation.",
    "I need a ride to a safe place.",
    "I require immediate help with evacuation.",
    "I need transportation assistance to leave the area.",
    "I require a vehicle to escape the disaster zone.",
    "I need help evacuating to safety.",
    "I require transport from this dangerous area.",
    "I need a ride for evacuation right away.",
    "I require urgent evacuation transport to safety.",
    "I need help leaving this hazardous area.",
    "I require a vehicle to help me move to safety.",
    "I need evacuation assistance from this dangerous zone.",
    "I require immediate transport to a safe refuge.",
    "I need help with evacuation logistics.",
    "I require transportation to get out of danger.",
    "I need a ride to evacuate safely.",
    "I require urgent transport to leave this area.",
    "I need help evacuating from the hazardous area.",
    "I require a vehicle for emergency evacuation.",
    "I need transportation to escape this dangerous place.",
    "I require immediate help to evacuate.",
    "I need a ride to get to safety now.",
    "I require urgent evacuation support via transport.",
    "I need help moving to a safe zone.",
    "I require a vehicle to help me evacuate immediately.",
    "I need transportation to leave this unsafe area.",
    "I require urgent help with evacuation transport.",
    "I need a ride for evacuation from this zone.",
    "I require immediate transportation to escape danger.",
    "I need help evacuating to a secure location.",
    "I require transport to move to safety.",
    "I need a vehicle for rapid evacuation.",
    "I require urgent help to leave this hazardous area.",
    "I need transportation assistance to get out safely.",
    "I require a ride to evacuate quickly.",
    "I need help with immediate evacuation logistics.",
    "I require transport from this dangerous area immediately.",
    "I need a vehicle to help me evacuate without delay.",
    "I require urgent transportation to a secure refuge.",
    "I need help leaving this area as soon as possible.",
    "I require a ride for quick evacuation.",
    "I need transportation to escape this unsafe zone.",
    "I require urgent help with evacuation from here.",
    "I need a vehicle to move to safety promptly.",
    "I require immediate evacuation transport assistance.",
    "I need help getting a ride to a safe area.",
    "I require urgent transport to evacuate from this disaster area."
]

# 5. Financial Assistance (Seeks money for survival or rebuilding)
financial_assistance_examples = [
    "I urgently need financial assistance to survive.",
    "I require money to rebuild my life after the disaster.",
    "I need immediate funds for survival.",
    "I require financial support to cover my basic needs.",
    "I need money for emergency expenses.",
    "I require financial aid to get through this crisis.",
    "I need funds for food, shelter, and recovery.",
    "I require money for survival and rebuilding.",
    "I need immediate financial help.",
    "I require emergency funds for essential expenses.",
    "I need financial support to rebuild my home.",
    "I require money to cover my living costs.",
    "I need assistance with financial aid.",
    "I require funds to secure a place to live.",
    "I need money urgently for basic survival.",
    "I require financial help for essential needs.",
    "I need funds to get back on my feet.",
    "I require money for emergency rebuilding.",
    "I need immediate financial aid.",
    "I require funds to cover my medical and living expenses.",
    "I need financial assistance to survive this crisis.",
    "I require money to pay for essential services.",
    "I need help with financial support.",
    "I require funds to secure my future.",
    "I need money for emergency survival.",
    "I require financial assistance to rebuild my life.",
    "I need funds for necessary expenses.",
    "I require money urgently for survival.",
    "I need financial support to cover basic costs.",
    "I require funds for essential survival needs.",
    "I need money to help with my recovery.",
    "I require financial aid for urgent expenses.",
    "I need funds to cover food and shelter costs.",
    "I require money to help rebuild my home.",
    "I need emergency financial assistance.",
    "I require funds to manage my living expenses.",
    "I need money for basic survival necessities.",
    "I require financial support to rebuild after the disaster.",
    "I need funds immediately for essential needs.",
    "I require money to survive this emergency.",
    "I need financial aid to cover my urgent expenses.",
    "I require funds for survival and recovery.",
    "I need money to pay for basic living costs.",
    "I require emergency financial support.",
    "I need funds to help me rebuild.",
    "I require financial assistance to manage essential expenses.",
    "I need money for immediate survival needs.",
    "I require funds to secure basic necessities.",
    "I need financial support to overcome this crisis.",
    "I require money to rebuild my life.",
    "I need funds to cover emergency survival costs.",
    "I require financial aid for essential rebuilding.",
    "I need money urgently to cover my basic needs.",
    "I require funds for urgent survival expenses.",
    "I need financial assistance for immediate recovery.",
    "I require money to secure a basic standard of living.",
    "I need funds for emergency support.",
    "I require financial support to cover essential expenses.",
    "I need money to help me survive this crisis.",
    "I require funds for urgent rebuilding and recovery.",
    "I need financial aid to cover my essential costs.",
    "I require money for immediate survival and rebuilding.",
    "I need funds to manage emergency expenses.",
    "I require financial assistance to secure my survival.",
    "I need money to cover my immediate needs.",
    "I require funds for basic emergency expenses.",
    "I need financial help to get through this disaster.",
    "I require money to rebuild and recover.",
    "I need funds for essential living expenses.",
    "I require financial aid to survive the crisis.",
    "I need money for immediate basic necessities.",
    "I require funds to help secure a stable future.",
    "I need financial support to cover survival costs.",
    "I require money to manage urgent living expenses.",
    "I need funds to help me survive this emergency.",
    "I require financial assistance for essential recovery.",
    "I need money to pay for my basic survival needs.",
    "I require funds to help me rebuild my life.",
    "I need financial aid for immediate emergency expenses.",
    "I require money to cover my urgent essential costs.",
    "I need funds to support my survival and recovery.",
    "I require financial support to get through this crisis.",
    "I need money to help pay for basic necessities.",
    "I require funds to cover emergency rebuilding expenses.",
    "I need financial aid for urgent survival.",
    "I require money to secure basic emergency support.",
    "I need funds to help cover my living expenses.",
    "I require financial assistance to help me recover.",
    "I need money for immediate support during the crisis.",
    "I require funds to cover essential survival and rebuilding costs.",
    "I need financial support to help me manage urgent expenses.",
    "I require money for emergency survival and recovery.",
    "I need funds to help secure a basic standard of living.",
    "I require financial aid to overcome my current crisis.",
    "I need money to help with immediate rebuilding needs.",
    "I require funds for urgent basic survival expenses.",
    "I need financial assistance to cover my recovery costs.",
    "I require money to manage essential emergency expenses.",
    "I need funds to help secure my survival during this crisis.",
    "I require financial support to rebuild and survive."
]

# 6. Supplies (Needs clothing, blankets, hygiene kits, etc.)
supplies_examples = [
    "I urgently need supplies like clothing and blankets.",
    "I require essential supplies such as hygiene kits.",
    "I need help with obtaining necessary supplies.",
    "I require emergency supplies including blankets and clothing.",
    "I need essential items like food, water, and hygiene kits.",
    "I require supplies to keep warm and clean.",
    "I need help getting clothing and essential supplies.",
    "I require basic supplies like blankets and toiletries.",
    "I need urgent support with necessary supplies.",
    "I require emergency items like clothing and hygiene products.",
    "I need essential supplies to stay warm.",
    "I require necessary items including blankets and clothing.",
    "I need help obtaining hygiene kits and supplies.",
    "I require supplies such as clothing and basic necessities.",
    "I need urgent assistance with supplies.",
    "I require essential items like blankets and hygiene kits.",
    "I need help getting supplies to meet basic needs.",
    "I require emergency clothing and essential supplies.",
    "I need support with supplies like blankets and toiletries.",
    "I require urgent help with essential items.",
    "I need supplies for warmth and hygiene.",
    "I require essential supplies including clothing.",
    "I need help obtaining basic items like blankets.",
    "I require emergency supplies to stay clean and warm.",
    "I need urgent support with necessary clothing.",
    "I require essential supplies for survival.",
    "I need help with supplies like hygiene kits.",
    "I require basic necessities like clothing and blankets.",
    "I need emergency support with essential supplies.",
    "I require supplies such as hygiene products and clothing.",
    "I need help obtaining necessary items for survival.",
    "I require essential supplies to stay warm and healthy.",
    "I need urgent assistance with clothing and blankets.",
    "I require basic supplies like toiletries and hygiene kits.",
    "I need help with emergency supplies.",
    "I require necessary items such as clothing and blankets.",
    "I need support with obtaining essential supplies.",
    "I require supplies for basic survival needs.",
    "I need help with clothing, blankets, and hygiene kits.",
    "I require emergency supplies to maintain hygiene.",
    "I need essential items like blankets and toiletries.",
    "I require supplies to stay warm during the crisis.",
    "I need help obtaining basic survival supplies.",
    "I require emergency clothing and hygiene products.",
    "I need urgent support with essential items.",
    "I require supplies such as clothing and basic necessities.",
    "I need help with acquiring essential supplies.",
    "I require necessary items like blankets and hygiene kits.",
    "I need emergency support with supplies.",
    "I require basic supplies to help me survive.",
    "I need help obtaining items like clothing and toiletries.",
    "I require essential supplies including blankets and hygiene products.",
    "I need urgent assistance with emergency supplies.",
    "I require necessary supplies to stay warm and clean.",
    "I need help with basic items such as clothing.",
    "I require emergency supplies like blankets and hygiene kits.",
    "I need essential items to maintain basic health.",
    "I require supplies to stay healthy during this crisis.",
    "I need help acquiring necessary survival supplies.",
    "I require essential items like clothing, blankets, and toiletries.",
    "I need emergency support with basic supplies.",
    "I require necessary supplies to meet my basic needs.",
    "I need help with obtaining essential items for hygiene.",
    "I require supplies such as clothing and survival essentials.",
    "I need urgent assistance with acquiring emergency supplies.",
    "I require basic survival supplies including blankets.",
    "I need help with essential items to stay warm.",
    "I require emergency supplies for basic hygiene.",
    "I need essential supplies to help me survive the crisis.",
    "I require support with obtaining necessary clothing and blankets.",
    "I need help with emergency survival supplies.",
    "I require necessary items like hygiene kits and clothing.",
    "I need essential supplies to maintain warmth and cleanliness.",
    "I require supplies to help me manage during the crisis.",
    "I need help with acquiring basic necessities like clothing.",
    "I require emergency supplies including blankets and toiletries.",
    "I need essential items to keep me warm.",
    "I require supplies such as clothing and hygiene products.",
    "I need help obtaining necessary emergency supplies.",
    "I require basic survival items like blankets and clothing.",
    "I need urgent support with essential survival supplies.",
    "I require supplies for basic health and hygiene.",
    "I need help with acquiring items such as hygiene kits.",
    "I require essential supplies including clothing and blankets.",
    "I need help obtaining emergency survival items.",
    "I require necessary supplies for warmth and hygiene.",
    "I need urgent assistance with basic items like clothing.",
    "I require supplies such as blankets, clothing, and toiletries.",
    "I need help with emergency supplies for survival.",
    "I require essential items to stay warm during the crisis.",
    "I need help acquiring basic survival supplies.",
    "I require supplies like hygiene kits and essential clothing.",
    "I need urgent support with emergency supplies.",
    "I require necessary items to maintain basic hygiene.",
    "I need help with essential supplies for survival.",
    "I require basic supplies such as clothing and blankets.",
    "I need emergency support with acquiring necessary items.",
    "I require supplies to help me maintain warmth and cleanliness.",
    "I need help with essential emergency survival supplies.",
    "I require urgent assistance with necessary supplies."
]
